name: "Test Jumpstarter workflow"
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  test-in-hardware:
    runs-on: [self-hosted, linux, jumpstarter-rpi4]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Worker local cache
        run: |
          mkdir -p $HOME/.cache/dl.fedoraproject.org
          ln -s $HOME/.cache/dl.fedoraproject.org images/dl.fedoraproject.org

      - name: List devices
        run: jumpstarter list-devices

      - name: Download images
        run: make download-image

      - name: Prepare image
        run: make prepare-image

      - name: Test in Hardware
        run: make test-in-hardware
